# Welcome to Jekyll!
#

# Site settings
title: MálagaJam
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: MálagaJam # or company name
first_published: 2018 # if migrating another site, the year of your first publish
email: info@malagajam.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/malagajam
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/malagajam
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  youtube-square: https://www.youtube.com/channel/UCmQ_zibc3cteype4pYYWj0w
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  slack: https://jamses.slack.com/
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
